#files <- list.files(path="data/", pattern="*.csv")
data = read.csv("../data/result1000000.txt")
print("TAMANHO DO ARRAY: 1000000")
std <- function(x) sd(x)/sqrt(length(x))
print("-------------------------------- SEQUENCIAL")
setNames(aggregate(data$sequencial,by=list(data$tamanho),FUN=mean), c("Tamanho", "Media"))
setNames(aggregate(data$sequencial,by=list(data$tamanho),FUN=sd), c("Tamanho", "Desvio"))
setNames(aggregate(data$sequencial,by=list(data$tamanho),FUN=std), c("Tamanho", "Erro"))
print("-------------------------------- SEQUENCIAL LIBC")
setNames(aggregate(data$libc,by=list(data$tamanho),FUN=mean), c("tamanho", "Media"))
setNames(aggregate(data$libc,by=list(data$tamanho),FUN=sd), c("tamanho", "Desvio"))
setNames(aggregate(data$libc,by=list(data$tamanho),FUN=std), c("tamanho", "Erro"))
print("-------------------------------- PARALELO")
setNames(aggregate(data$paralelo,by=list(data$thread),FUN=mean), c("# de Thread", "Media"))
setNames(aggregate(data$paralelo,by=list(data$thread),FUN=sd), c("# de Thread", "Desvio"))
setNames(aggregate(data$paralelo,by=list(data$thread),FUN=std), c("# de Thread", "Erro"))

